# Generated by Django 3.2.11 on 2022-01-30 09:09

import core_lms.validators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20220123_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='inn',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(120), core_lms.validators.even_integer_validator]),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 9, 9, 8, 847682)),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('^(\\+\\d\\d?)?\\(\\d{3}\\)(\\d-?){7}$', message='Phone number should be in format +1(111)222-33-44')]),
        ),
    ]
