# Generated by Django 3.2.11 on 2022-02-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('students', models.ManyToManyField(related_name='lectures', to='students.Student')),
            ],
        ),
    ]
