# Generated by Django 3.2.11 on 2022-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_lecture_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='students.Student'),
        ),
    ]
