image: python:latest

before_script:
  - python --version  # For debugging
  - python -m venv env
  - source env/bin/activate

test:
  script:
    - flake8

run:
  script:
    - pip install -r requirements.txt
