version: "3"

services:
  broker:
    image: rabbitmq:3.10.2-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"

  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example-password
      POSTGRES_USER: exampleUser
      POSTGRES_DB: exampleUser
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}