# Generated by Django 3.2.11 on 2022-02-02 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('course', models.CharField(max_length=64)),
                ('start_date', models.DateField(default=datetime.datetime(2022, 2, 2, 16, 29, 15, 196637))),
            ],
        ),
    ]
